# TWRP Board Configuration for Samsung Galaxy M02 (SM-M022G)
DEVICE_PATH := device/samsung/m02

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a53

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := mt6739

# Platform
TARGET_BOARD_PLATFORM := mt6739

# Kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32S1,32S1
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x40008000
BOARD_RAMDISK_OFFSET := 0x45000000
BOARD_TAGS_OFFSET := 0x44000000
BOARD_KERNEL_IMAGE_NAME := kernel
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/kernel

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_FLASH_BLOCK_SIZE := 131072

# TWRP Flags
TW_NO_SYSTEM_ROOT := true
TW_USE_TOOLBOX := true
TW_THEME := portrait_hdpi
TW_EXCLUDE_TWRPAPP := true
TW_INCLUDE_RESETPROP := true

# MediaTek
BOARD_USES_MTK_HARDWARE := true
